// Writes `.cursor/rules/<id>.mdc` (fully generated) and a fenced section in
// `.github/copilot-instructions.md` (marker-based, like AGENTS.md), both carrying a shorter
// version of the same routine text as agents-md.ts and skill.ts.

import { resolve } from 'node:path';
import type { SystemData } from '../types.ts';
import {
  GENERATED_SIGNATURE,
  NEVER_INVENT_RULE,
  beginMarker,
  consumptionLine,
  endMarker,
  frontMatterBlock,
  routineSteps,
  writeGenerated,
  writeMarkedFile,
} from './shared.ts';

function isGenerated(content: string): boolean {
  return content.includes(GENERATED_SIGNATURE);
}

function routineLines(data: SystemData): string[] {
  return routineSteps(data).map((step, i) => `${i + 1}. **${step.tool}** -- ${step.when}`);
}

export function buildCursorRule(data: SystemData): string {
  const name = data.cfg.name ?? data.id;
  const description = `Design system routine for ${name}: search before writing, resolve before importing, find_token instead of raw values, never invent API.`;

  const lines: string[] = [
    frontMatterBlock({
      description,
      globs: ['**/*.tsx', '**/*.ts', '**/*.html'],
      alwaysApply: 'false',
      generated: GENERATED_SIGNATURE,
    }),
    '',
    `# ${name}`,
    '',
    consumptionLine(data),
    '',
    'Routine:',
    '',
    ...routineLines(data),
    '',
    NEVER_INVENT_RULE,
  ];

  return `${lines.join('\n')}\n`;
}

export function buildCopilotSection(data: SystemData): string {
  const name = data.cfg.name ?? data.id;
  const lines: string[] = [
    beginMarker(data.id),
    `## ${name} (design system)`,
    '',
    consumptionLine(data),
    '',
    'Routine:',
    '',
    ...routineLines(data),
    '',
    NEVER_INVENT_RULE,
    '',
    endMarker(data.id),
  ];
  return lines.join('\n');
}

export interface EditorRulesResult {
  written: string[];
  skipped: string[];
  notes: string[];
}

export function writeEditorRules(data: SystemData, outDir: string, opts?: { force?: boolean }): EditorRulesResult {
  const written: string[] = [];
  const skipped: string[] = [];
  const notes: string[] = [];

  const cursorPath = resolve(outDir, '.cursor/rules', `${data.id}.mdc`);
  const cursorAction = writeGenerated(cursorPath, buildCursorRule(data), { force: opts?.force, isGenerated });
  (cursorAction === 'written' ? written : skipped).push(cursorPath);

  const copilotPath = resolve(outDir, '.github/copilot-instructions.md');
  writeMarkedFile(copilotPath, data.id, buildCopilotSection(data), { createIfMissing: true });
  written.push(copilotPath);

  if (skipped.length > 0) {
    notes.push(`Left alone, not generated by this tool before (pass force to overwrite): ${skipped.join(', ')}`);
  }

  return { written, skipped, notes };
}
