import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { test } from 'node:test';

import { makeSystemData } from '../test-helpers.ts';
import { runGenerate } from './index.ts';

function tempDir(): string {
  return mkdtempSync(join(tmpdir(), 'ds-mcp-generate-'));
}

function parseFrontMatter(content: string): Record<string, string> {
  const match = /^---\n([\s\S]*?)\n---/.exec(content);
  assert.ok(match, 'expected a leading --- front-matter block');
  const fields: Record<string, string> = {};
  for (const line of match![1]!.split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) {
      value = JSON.parse(value);
    }
    fields[key] = value;
  }
  return fields;
}

test('agents-md: creates AGENTS.md with a fenced section, never touches a missing CLAUDE.md', () => {
  const data = makeSystemData();
  const out = tempDir();
  const result = runGenerate(data, { target: 'agents-md', outDir: out });

  const agentsPath = resolve(out, 'AGENTS.md');
  assert.ok(result.written.includes(agentsPath));
  assert.equal(existsSync(resolve(out, 'CLAUDE.md')), false);

  const content = readFileSync(agentsPath, 'utf8');
  assert.match(content, /<!-- ds-mcp:begin acme -->/);
  assert.match(content, /<!-- ds-mcp:end acme -->/);
  assert.match(content, /search_components/);
  assert.match(content, /resolve_component/);
  assert.match(content, /find_token/);
});

test('agents-md: updates CLAUDE.md only when it already exists, preserving surrounding text', () => {
  const data = makeSystemData();
  const out = tempDir();
  const claudePath = resolve(out, 'CLAUDE.md');
  writeFileSync(claudePath, '# Team notes\n\nHand-written content stays here.\n', 'utf8');

  runGenerate(data, { target: 'agents-md', outDir: out });

  const content = readFileSync(claudePath, 'utf8');
  assert.match(content, /Hand-written content stays here\./);
  assert.match(content, /<!-- ds-mcp:begin acme -->/);
  assert.match(content, /<!-- ds-mcp:end acme -->/);
});

test('agents-md: a second run with changed data replaces the section instead of duplicating it', () => {
  const out = tempDir();
  const data1 = makeSystemData();
  runGenerate(data1, { target: 'agents-md', outDir: out });

  const data2 = makeSystemData({ cfg: { ...data1.cfg, name: 'Acme Elements Renamed' } });
  runGenerate(data2, { target: 'agents-md', outDir: out });

  const content = readFileSync(resolve(out, 'AGENTS.md'), 'utf8');
  const beginCount = content.split('<!-- ds-mcp:begin acme -->').length - 1;
  const endCount = content.split('<!-- ds-mcp:end acme -->').length - 1;
  assert.equal(beginCount, 1);
  assert.equal(endCount, 1);
  assert.match(content, /Acme Elements Renamed/);
});

test('llms-txt: writes both files and reports their sizes', () => {
  const data = makeSystemData();
  const out = tempDir();
  const result = runGenerate(data, { target: 'llms-txt', outDir: out });

  const shortPath = resolve(out, 'llms.txt');
  const fullPath = resolve(out, 'llms-full.txt');
  assert.ok(result.written.includes(shortPath));
  assert.ok(result.written.includes(fullPath));

  const shortText = readFileSync(shortPath, 'utf8');
  assert.match(shortText, /Surface/); // a real component name from makeSystemData
  assert.match(shortText, /ds:\/\/acme\/components\/Surface/);

  const fullText = readFileSync(fullPath, 'utf8');
  assert.match(fullText, /## Tokens/);
  assert.match(fullText, /Props:/);

  const sizeNote = result.notes.find((n) => n.includes('llms.txt') && n.includes('KB'));
  assert.ok(sizeNote, `expected a size note, got: ${result.notes.join(' | ')}`);
  assert.match(sizeNote!, /llms\.txt \d+(\.\d+)? KB, llms-full\.txt \d+(\.\d+)? KB/);
});

test('llms-txt: force overwrites a pre-existing file; without force it is left alone and reported as skipped', () => {
  const data = makeSystemData();
  const out = tempDir();
  const llmsPath = resolve(out, 'llms.txt');
  writeFileSync(llmsPath, 'hand-written, not generated by this tool\n', 'utf8');

  const withoutForce = runGenerate(data, { target: 'llms-txt', outDir: out });
  assert.ok(withoutForce.skipped.includes(llmsPath));
  assert.ok(!withoutForce.written.includes(llmsPath));
  assert.equal(readFileSync(llmsPath, 'utf8'), 'hand-written, not generated by this tool\n');

  const withForce = runGenerate(data, { target: 'llms-txt', outDir: out, force: true });
  assert.ok(withForce.written.includes(llmsPath));
  assert.notEqual(readFileSync(llmsPath, 'utf8'), 'hand-written, not generated by this tool\n');
});

test('llms-txt: a plain re-run (no force) updates a file this tool generated before', () => {
  const data = makeSystemData();
  const out = tempDir();
  runGenerate(data, { target: 'llms-txt', outDir: out });

  const data2 = makeSystemData({ cfg: { ...data.cfg, name: 'Acme Elements Renamed' } });
  const result = runGenerate(data2, { target: 'llms-txt', outDir: out });

  assert.ok(result.written.includes(resolve(out, 'llms.txt')));
  const content = readFileSync(resolve(out, 'llms.txt'), 'utf8');
  assert.match(content, /Acme Elements Renamed/);
});

test('skill: writes use-<id> and review-<id> SKILL.md with front matter whose name matches its directory', () => {
  const data = makeSystemData();
  const out = tempDir();
  const result = runGenerate(data, { target: 'skill', outDir: out });

  const usePath = resolve(out, '.claude/skills/use-acme/SKILL.md');
  const reviewPath = resolve(out, '.claude/skills/review-acme/SKILL.md');
  assert.ok(result.written.includes(usePath));
  assert.ok(result.written.includes(reviewPath));

  const useFront = parseFrontMatter(readFileSync(usePath, 'utf8'));
  assert.equal(useFront.name, 'use-acme');
  assert.ok(useFront.description && useFront.description.length > 0);

  const reviewFront = parseFrontMatter(readFileSync(reviewPath, 'utf8'));
  assert.equal(reviewFront.name, 'review-acme');

  const useBody = readFileSync(usePath, 'utf8');
  assert.match(useBody, /search_components/);
  assert.match(useBody, /find_token/);

  const reviewBody = readFileSync(reviewPath, 'utf8');
  assert.match(reviewBody, /check_usage/);
});

test('editor-rules: writes a .cursor rule with parseable front matter and a copilot-instructions.md fenced section', () => {
  const data = makeSystemData();
  const out = tempDir();
  const result = runGenerate(data, { target: 'editor-rules', outDir: out });

  const cursorPath = resolve(out, '.cursor/rules/acme.mdc');
  const copilotPath = resolve(out, '.github/copilot-instructions.md');
  assert.ok(result.written.includes(cursorPath));
  assert.ok(result.written.includes(copilotPath));

  const cursorFront = parseFrontMatter(readFileSync(cursorPath, 'utf8'));
  assert.ok(cursorFront.description);
  assert.equal(cursorFront.alwaysApply, 'false');

  const copilotContent = readFileSync(copilotPath, 'utf8');
  assert.match(copilotContent, /<!-- ds-mcp:begin acme -->/);
  assert.match(copilotContent, /<!-- ds-mcp:end acme -->/);
});

test('well-known: servers.json is valid JSON and carries the server command', () => {
  const data = makeSystemData();
  const out = tempDir();
  const result = runGenerate(data, { target: 'well-known', outDir: out, serverCommand: 'npx tsx /abs/src/cli.ts serve --config /abs/ds.config.json' });

  const path = resolve(out, '.well-known/mcp/servers.json');
  assert.ok(result.written.includes(path));

  const json = JSON.parse(readFileSync(path, 'utf8')) as { servers: Array<{ name: string; transport: { type: string; command: string; args: string[] } }> };
  assert.equal(json.servers.length, 1);
  const server = json.servers[0]!;
  assert.equal(server.name, 'acme');
  assert.equal(server.transport.type, 'stdio');
  assert.equal(server.transport.command, 'npx');
  assert.deepEqual(server.transport.args, ['tsx', '/abs/src/cli.ts', 'serve', '--config', '/abs/ds.config.json']);
  assert.ok(result.notes.some((n) => n.includes('P3')));
});

test('well-known: adds a streamable-http url when serverUrl is given', () => {
  const data = makeSystemData();
  const out = tempDir();
  runGenerate(data, { target: 'well-known', outDir: out, serverUrl: 'https://mcp.example.internal/acme' });

  const json = JSON.parse(readFileSync(resolve(out, '.well-known/mcp/servers.json'), 'utf8')) as {
    servers: Array<{ url?: string; remoteTransport?: { type: string; url: string } }>;
  };
  assert.equal(json.servers[0]!.url, 'https://mcp.example.internal/acme');
  assert.equal(json.servers[0]!.remoteTransport?.type, 'streamable-http');
});

test('all: writes every generated file for the system in one call', () => {
  const data = makeSystemData();
  const out = tempDir();
  const result = runGenerate(data, { target: 'all', outDir: out });

  const expected = [
    resolve(out, 'AGENTS.md'),
    resolve(out, 'llms.txt'),
    resolve(out, 'llms-full.txt'),
    resolve(out, '.claude/skills/use-acme/SKILL.md'),
    resolve(out, '.claude/skills/review-acme/SKILL.md'),
    resolve(out, '.cursor/rules/acme.mdc'),
    resolve(out, '.github/copilot-instructions.md'),
    resolve(out, '.well-known/mcp/servers.json'),
  ];
  for (const path of expected) {
    assert.ok(result.written.includes(path), `expected ${path} to be written`);
    assert.ok(existsSync(path), `expected ${path} to exist on disk`);
  }
});

test('custom-elements system: consumption rule and routine reflect the tag model, not react imports', () => {
  const data = makeSystemData({ model: 'custom-elements' });
  const out = tempDir();
  runGenerate(data, { target: 'agents-md', outDir: out });

  const content = readFileSync(resolve(out, 'AGENTS.md'), 'utf8');
  assert.match(content, /Register once by importing/);
  assert.doesNotMatch(content, /import \{ acme-surface \}/);
});
