// Entry point for the `generate` command: writes the agent-facing surface (AGENTS.md
// section, llms.txt/llms-full.txt, the use-<id>/review-<id> skills, editor rules, and
// .well-known/mcp) for one already-loaded system into an adopting team's repo. Pure file
// writes over SystemData; no network, no MCP server dependency, no CLI parsing here -- the
// orchestrator (src/cli.ts) resolves a system from the registry and calls `runGenerate`.

import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { SystemData } from '../types.ts';
import { writeAgentsMd } from './agents-md.ts';
import { writeEditorRules } from './editor-rules.ts';
import { writeLlmsTxt } from './llms-txt.ts';
import { writeSkills } from './skill.ts';
import { writeWellKnown } from './well-known.ts';

export type GenerateTarget = 'agents-md' | 'llms-txt' | 'skill' | 'editor-rules' | 'well-known' | 'all';

export interface GenerateOptions {
  target: GenerateTarget;
  /** Where the adopting team's repo lives (their design system repo or app) -- not this repo. */
  outDir: string;
  /** The command a client should run to start this server. Defaults to this repo's own src/cli.ts and ds.config.json, as absolute paths. */
  serverCommand?: string;
  /** A streamable-http URL for a shared instance, when one exists (see well-known.ts). */
  serverUrl?: string;
  /** Overwrite an existing file at a generated path even when it was not generated by this tool before. */
  force?: boolean;
}

export interface GenerateResult {
  written: string[];
  skipped: string[];
  notes: string[];
}

const ALL_TARGETS: readonly Exclude<GenerateTarget, 'all'>[] = ['agents-md', 'llms-txt', 'skill', 'editor-rules', 'well-known'];

/** This repo's own src/cli.ts and ds.config.json, resolved from this module's location. */
function repoDefaults(): { cliPath: string; configPath: string } {
  const here = fileURLToPath(import.meta.url); // .../src/generate/index.ts
  const repoRoot = resolve(here, '..', '..', '..');
  return { cliPath: resolve(repoRoot, 'src/cli.ts'), configPath: resolve(repoRoot, 'ds.config.json') };
}

/** `npx tsx <abs>/src/cli.ts serve --config <abs>/ds.config.json`, built from this repo's own location. */
export function defaultServerCommand(): string {
  const { cliPath, configPath } = repoDefaults();
  return `npx tsx ${cliPath} serve --config ${configPath}`;
}

function mergeResults(results: GenerateResult[]): GenerateResult {
  return {
    written: results.flatMap((r) => r.written),
    skipped: results.flatMap((r) => r.skipped),
    notes: results.flatMap((r) => r.notes),
  };
}

/** Writes the requested generated surface for one system into `opts.outDir`. */
export function runGenerate(data: SystemData, opts: GenerateOptions): GenerateResult {
  const serverCommand = opts.serverCommand ?? defaultServerCommand();
  const targets = opts.target === 'all' ? ALL_TARGETS : [opts.target];

  const results = targets.map((target): GenerateResult => {
    switch (target) {
      case 'agents-md':
        return writeAgentsMd(data, opts.outDir, serverCommand);
      case 'llms-txt':
        return writeLlmsTxt(data, opts.outDir, { force: opts.force });
      case 'skill':
        return writeSkills(data, opts.outDir, { force: opts.force });
      case 'editor-rules':
        return writeEditorRules(data, opts.outDir, { force: opts.force });
      case 'well-known':
        return writeWellKnown(data, opts.outDir, { serverCommand, serverUrl: opts.serverUrl, force: opts.force });
      default: {
        const _exhaustive: never = target;
        throw new Error(`Unknown generate target: ${String(_exhaustive)}`);
      }
    }
  });

  return mergeResults(results);
}
