// Writes the two generated skills for one system: `use-<id>` (the agent's build routine,
// concrete tool calls, aliases, and a few do/don'ts pulled from the real catalog) and
// `review-<id>` (how to review a diff against the system). Both are fully-generated
// SKILL.md files -- see `writeGenerated` in shared.ts for the force/skip behavior.

import { resolve } from 'node:path';
import type { SystemData } from '../types.ts';
import {
  GENERATED_SIGNATURE,
  consumptionLine,
  derivedDoDont,
  frontMatterBlock,
  routineSteps,
  teamAliasRows,
  writeGenerated,
} from './shared.ts';

function isGenerated(content: string): boolean {
  return content.includes(GENERATED_SIGNATURE);
}

export function buildUseSkill(data: SystemData): string {
  const name = data.cfg.name ?? data.id;
  const skillName = `use-${data.id}`;
  const description = `Use when building or changing UI with ${name}: search before writing, resolve before importing, and never invent a component, prop, or raw value.`;

  const lines: string[] = [
    frontMatterBlock({ name: skillName, description, generated: GENERATED_SIGNATURE }),
    '',
    `# Using ${name}`,
    '',
    consumptionLine(data),
    '',
    '## Routine',
    '',
  ];

  routineSteps(data).forEach((step, i) => {
    lines.push(`${i + 1}. **${step.tool}** -- ${step.when}`);
    lines.push(`   \`${step.example}\``);
  });

  const aliasRows = teamAliasRows(data).slice(0, 8);
  if (aliasRows.length > 0) {
    lines.push('', '## This system calls it', '');
    for (const row of aliasRows) {
      lines.push(`- ${row.alias} -> ${row.target}${row.note ? ` (${row.note})` : ''}`);
    }
  }

  const doDont = derivedDoDont(data);
  if (doDont.length > 0) {
    lines.push('', "## Do / don't", '');
    for (const d of doDont) lines.push(`- ${d.kind === 'do' ? 'Do' : "Don't"} ${d.text}`);
  }

  lines.push(
    '',
    'Never guess. A lookup miss means the concept does not exist here, or needs a different name -- it is never permission to invent one.',
  );

  return `${lines.join('\n')}\n`;
}

export function buildReviewSkill(data: SystemData): string {
  const name = data.cfg.name ?? data.id;
  const skillName = `review-${data.id}`;
  const description = `Use when reviewing a diff that touches ${name}: run check_usage per changed file, explain each finding with its fix, and refuse to approve unknown components, raw values, or missing accessible names.`;

  const lines: string[] = [
    frontMatterBlock({ name: skillName, description, generated: GENERATED_SIGNATURE }),
    '',
    `# Reviewing against ${name}`,
    '',
    `Run this whenever a diff touches ${name}, before approving it.`,
    '',
    '## Steps',
    '',
    "1. For every changed file that imports or renders the system, call `check_usage` with that file's code and language.",
    "2. For each finding, explain it in plain terms and give the fix the catalog reports (the finding's `fix`), never a guessed alternative.",
    "3. Treat `unknown-component` and `invented-prop` findings as blocking: never approve a diff that writes API this system does not have.",
    '4. Treat a `raw-value` finding as blocking: a hardcoded color or length belongs in `find_token` output instead.',
    '5. Treat `missing-accessible-name` as blocking when `get_component` reports that component\'s `accessibleName` as `required`, and worth a comment when `recommended`.',
    "6. A `deprecated` finding is not automatically blocking, but the review must name the replacement (`get_migration`, or the catalog's `deprecated.replacement`) rather than let it pass silently.",
    "7. If `usedComponents` is empty on a file that clearly renders UI, say so -- the design system was not used at all, which is worse than a small API mistake.",
    '',
    'Never approve a component, prop, or raw value this server does not confirm as real.',
  ];

  return `${lines.join('\n')}\n`;
}

export interface SkillResult {
  written: string[];
  skipped: string[];
  notes: string[];
}

export function writeSkills(data: SystemData, outDir: string, opts?: { force?: boolean }): SkillResult {
  const written: string[] = [];
  const skipped: string[] = [];

  const usePath = resolve(outDir, '.claude/skills', `use-${data.id}`, 'SKILL.md');
  const reviewPath = resolve(outDir, '.claude/skills', `review-${data.id}`, 'SKILL.md');

  const useAction = writeGenerated(usePath, buildUseSkill(data), { force: opts?.force, isGenerated });
  (useAction === 'written' ? written : skipped).push(usePath);

  const reviewAction = writeGenerated(reviewPath, buildReviewSkill(data), { force: opts?.force, isGenerated });
  (reviewAction === 'written' ? written : skipped).push(reviewPath);

  const notes: string[] = [];
  if (skipped.length > 0) {
    notes.push(`Left alone, not generated by this tool before (pass force to overwrite): ${skipped.join(', ')}`);
  }

  return { written, skipped, notes };
}
