// Writes `.well-known/mcp/servers.json`, following the common `.well-known/mcp` convention
// for a repo to advertise the MCP servers it offers. The stdio command is always listed --
// it works today, P0's only supported transport. A streamable-http `url` is added alongside
// it when the caller has one, since a shared hosted instance is planned for a later phase
// (P3) and this server does not speak it yet.

import { resolve } from 'node:path';
import type { SystemData } from '../types.ts';
import { GENERATED_SIGNATURE, writeGenerated } from './shared.ts';

function splitCommand(serverCommand: string): { command: string; args: string[] } {
  const parts = serverCommand.trim().split(/\s+/).filter(Boolean);
  const [command, ...args] = parts;
  return { command: command ?? serverCommand, args };
}

export function buildServersJson(data: SystemData, opts: { serverCommand: string; serverUrl?: string }): string {
  const { command, args } = splitCommand(opts.serverCommand);
  const name = data.cfg.name ?? data.id;

  const server: Record<string, unknown> = {
    name: data.id,
    title: name,
    description: data.cfg.description ?? `MCP server for ${name}.`,
    transport: { type: 'stdio', command, args },
  };
  if (opts.serverUrl) {
    server.url = opts.serverUrl;
    server.remoteTransport = { type: 'streamable-http', url: opts.serverUrl };
  }

  const doc = { $generatedBy: GENERATED_SIGNATURE, servers: [server] };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

function isGenerated(content: string): boolean {
  try {
    const json = JSON.parse(content) as { $generatedBy?: string };
    return json.$generatedBy === GENERATED_SIGNATURE;
  } catch {
    return content.includes(GENERATED_SIGNATURE);
  }
}

export interface WellKnownResult {
  written: string[];
  skipped: string[];
  notes: string[];
}

export function writeWellKnown(data: SystemData, outDir: string, opts: { serverCommand: string; serverUrl?: string; force?: boolean }): WellKnownResult {
  const path = resolve(outDir, '.well-known/mcp/servers.json');
  const content = buildServersJson(data, opts);
  const action = writeGenerated(path, content, { force: opts.force, isGenerated });

  const written = action === 'written' ? [path] : [];
  const skipped = action === 'skipped' ? [path] : [];
  const notes = [
    'Follows the common .well-known/mcp convention for a repo to advertise its MCP servers. Hosted (streamable-http) transport arrives in P3; only the stdio command is guaranteed to work with this starter today.',
  ];
  if (skipped.length > 0) {
    notes.push(`Left alone, not generated by this tool before (pass force to overwrite): ${skipped.join(', ')}`);
  }

  return { written, skipped, notes };
}
