// Command line entry: init | serve | extract | doctor | generate | overlay-scaffold.
//
// `serve` speaks MCP over stdio, so it must never print to stdout; every
// human-facing line goes to stderr. `extract` and `doctor` are ordinary
// commands and print to stdout.

import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { runExtract } from './adapters/index.ts';
import { loadDsConfig, resolveDataDir, resolveRoot } from './config.ts';
import { buildRegistry, checkFreshness, loadSystemData, overlayReport } from './data/load.ts';
import { writeOverlayScaffold } from './data/overlay.ts';
import { undocumentedValueExports } from './data/undocumented.ts';
import { startHttp } from './http.ts';
import { runGenerate, type GenerateTarget } from './generate/index.ts';
import { runInit } from './init/wizard.ts';
import { startStdio } from './server.ts';
import type { SystemId } from './types.ts';

const USAGE = `usage: npx tsx src/cli.ts <command> [options]

commands
  init       add a system to ds.config.json (interactive; --id with --root or --package for non-interactive)
  serve      start the MCP server over stdio, or over streamable HTTP with --http
  extract    build data/<system>/catalog.json and tokens.json from the configured adapters
  doctor     check config, source roots, data files and freshness
  generate   write the agent-facing surface for a system into a target repo:
             generate <agents-md|llms-txt|skill|editor-rules|well-known|all> --system <id> --target <dir>
  overlay-scaffold
             write data/<system>/overlay.json entries for exports the adapter could not document

options
  --config <path>   ds.config.json to use (default: ./ds.config.json)
  --system <id>     limit extract/doctor to one system
  --strict          serve: refuse to start when any system's data is stale
  --out <dir>       extract: write into this directory instead of the system's data dir
  --id <id>         init: system id (non-interactive when --root is also given)
  --root <path>     init: design system checkout to detect adapters in
  --package <name>  init: npm package installed in this folder to consume the system from
  --foundations <n> init: npm package holding the tokens CSS (optional, detected from peer deps)
  --http            serve: streamable HTTP instead of stdio (default port 3333, host 127.0.0.1, path /mcp)
  --port <n>        serve --http: port
  --host <h>        serve --http: bind address (0.0.0.0 to expose; set DS_MCP_TOKEN when you do)
  --path <p>        serve --http: URL path
  --target <dir>    generate: the repo to write into (default: current directory)
  --force           generate: overwrite files that were not generated by this tool
  --server-url <u>  generate: advertise a hosted streamable-http endpoint in .well-known
`;

function fail(message: string): never {
  process.stderr.write(`error: ${message}\n`);
  process.exit(1);
}

function main(): Promise<void> {
  const { values, positionals } = parseArgs({
    args: process.argv.slice(2),
    allowPositionals: true,
    options: {
      config: { type: 'string' },
      system: { type: 'string' },
      strict: { type: 'boolean', default: false },
      out: { type: 'string' },
      id: { type: 'string' },
      root: { type: 'string' },
      package: { type: 'string' },
      foundations: { type: 'string' },
      http: { type: 'boolean', default: false },
      port: { type: 'string' },
      host: { type: 'string' },
      path: { type: 'string' },
      target: { type: 'string' },
      force: { type: 'boolean', default: false },
      'server-url': { type: 'string' },
      help: { type: 'boolean', short: 'h', default: false },
    },
  });

  const command = positionals[0];
  if (values.help || !command) {
    process.stdout.write(USAGE);
    process.exit(command ? 0 : 1);
  }

  switch (command) {
    case 'init':
      return init(values.config, values.id, values.root, values.package, values.foundations);
    case 'serve':
      return serve(values.config, values.strict ?? false, values.http ? { port: Number(values.port ?? 3333), host: values.host, path: values.path } : undefined);
    case 'overlay-scaffold':
      return overlayScaffold(values.config, values.system, values.force ?? false);
    case 'extract':
      return extract(values.config, values.system, values.out);
    case 'doctor':
      return doctor(values.config, values.system);
    case 'generate':
      return generate(values.config, values.system, positionals[1], values.target, values.force ?? false, values['server-url']);
    default:
      return fail(`unknown command "${command}"\n\n${USAGE}`);
  }
}

function selectSystems(ids: SystemId[], only: string | undefined): SystemId[] {
  if (!only) return ids;
  if (!ids.includes(only)) fail(`system "${only}" is not configured (configured: ${ids.join(', ') || 'none'})`);
  return [only];
}

async function init(
  configPath: string | undefined,
  id: string | undefined,
  root: string | undefined,
  pkg: string | undefined,
  foundations: string | undefined,
): Promise<void> {
  const target = configPath ?? 'ds.config.json';
  const answers =
    id || root || pkg
      ? { systemId: id, root, package: pkg, foundationsPackage: foundations }
      : undefined;
  const result = await runInit({ configPath: target, answers, log: (line) => process.stdout.write(`${line}\n`) });
  process.stdout.write(`added "${result.systemId}" to ${result.configPath}\n`);
}

async function serve(
  configPath: string | undefined,
  strict: boolean,
  http: { port: number; host?: string; path?: string } | undefined,
): Promise<void> {
  const loaded = loadDsConfig(configPath);
  const registry = buildRegistry(loaded);

  let stale = 0;
  for (const id of registry.ids()) {
    const report = checkFreshness(registry.get(id));
    if (report.catalog === 'stale' || report.tokens === 'stale' || report.docs === 'stale' || report.codeConnect === 'stale') {
      stale += 1;
      process.stderr.write(`[ds-mcp] ${id}: data is stale (${report.details.join('; ')}). Run: npx tsx src/cli.ts extract --system ${id}\n`);
    }
  }
  if (stale > 0 && strict) fail(`${stale} system(s) have stale data and --strict is set`);

  process.stderr.write(`[ds-mcp] serving ${registry.ids().length} system(s): ${registry.ids().join(', ')}\n`);
  if (http) {
    const started = await startHttp(registry, { port: http.port, host: http.host, path: http.path, log: (line) => process.stderr.write(`[ds-mcp] ${line}\n`) });
    process.stderr.write(`[ds-mcp] listening on ${started.url} (health: GET /healthz)\n`);
    return;
  }
  await startStdio(registry);
}

async function overlayScaffold(configPath: string | undefined, system: string | undefined, force: boolean): Promise<void> {
  const loaded = loadDsConfig(configPath);
  const registry = buildRegistry(loaded);
  let data;
  try {
    data = registry.get(system);
  } catch (err) {
    fail((err as Error).message);
  }
  const result = writeOverlayScaffold(data.dataDir, data.catalog, { force });
  process.stdout.write(
    result.written
      ? `wrote ${result.path} with ${result.entries} entr${result.entries === 1 ? 'y' : 'ies'} to fill in\n`
      : `${result.path} is up to date (${result.entries} undocumented exports already listed)\n`,
  );
}

async function extract(configPath: string | undefined, only: string | undefined, out: string | undefined): Promise<void> {
  const loaded = loadDsConfig(configPath);
  const ids = selectSystems(Object.keys(loaded.config.systems), only);
  let failures = 0;
  for (const id of ids) {
    const cfg = loaded.config.systems[id]!;
    try {
      const result = runExtract(id, cfg, loaded.configDir, out ? { dataDir: out } : undefined);
      const components = result.catalog.components.reduce((n, c) => n + c.exports.length, 0);
      const tokens = result.tokens ? result.tokens.tokens.length : 0;
      const chunks = result.docs ? result.docs.chunks.length : 0;
      process.stdout.write(`${id}: ${components} exports, ${result.catalog.allExports.length} symbols, ${tokens} tokens, ${chunks} doc chunks\n`);
      for (const file of result.written) process.stdout.write(`  wrote ${file}\n`);
    } catch (err) {
      failures += 1;
      process.stderr.write(`${id}: extract failed: ${(err as Error).message}\n`);
    }
  }
  if (failures > 0) process.exit(1);
}

async function doctor(configPath: string | undefined, only: string | undefined): Promise<void> {
  let loaded;
  try {
    loaded = loadDsConfig(configPath);
  } catch (err) {
    fail(`config: ${(err as Error).message}`);
  }
  process.stdout.write(`config: ${loaded.configPath}\n`);

  const ids = selectSystems(Object.keys(loaded.config.systems), only);
  let problems = 0;
  const note = (ok: boolean, line: string) => {
    if (!ok) problems += 1;
    process.stdout.write(`  ${ok ? 'ok  ' : 'FAIL'} ${line}\n`);
  };

  for (const id of ids) {
    const cfg = loaded.config.systems[id]!;
    process.stdout.write(`\n${id}${cfg.name ? ` (${cfg.name})` : ''}\n`);

    const root = resolveRoot(cfg, loaded.configDir);
    if (root) note(existsSync(root), `root ${root}${existsSync(root) ? '' : ' does not exist'}`);
    else process.stdout.write(`  info no root configured (adapters that read source will not run)\n`);

    const dataDir = resolveDataDir(id, cfg, loaded.configDir);
    let data;
    try {
      data = loadSystemData(id, cfg, loaded.configDir);
    } catch (err) {
      note(false, `data ${dataDir}: ${(err as Error).message}`);
      continue;
    }

    const components = data.catalog.components.reduce((n, c) => n + c.exports.length, 0);
    const props = Object.values(data.catalog.allPropsByExport).reduce((n, p) => n + p.length, 0);
    note(components > 0, `catalog: ${components} exports, ${data.catalog.allExports.length} symbols, ${props} gradeable prop names`);
    const overlay = overlayReport(dataDir, data.catalog);
    if (overlay) {
      note(overlay.unknown.length === 0, `overlay: ${overlay.touched} exports enriched${overlay.unknown.length ? `, unknown names: ${overlay.unknown.join(', ')}` : ''}`);
    }
    const cc = data.catalog.source.codeConnect;
    if (cc) process.stdout.write(`  info code connect: ${cc.mapped} of ${components} documented exports mapped (${cc.files} files)\n`);
    const undocumented = undocumentedValueExports(data.catalog);
    if (undocumented.length > 0) process.stdout.write(`  info ${undocumented.length} exports have no props table (run overlay-scaffold to list them): ${undocumented.slice(0, 5).join(', ')}${undocumented.length > 5 ? ', ...' : ''}\n`);
    if (data.tokens) note(data.tokens.tokens.length > 0, `tokens: ${data.tokens.tokens.length} (${data.tokens.themes?.join(', ') || 'single theme'})`);
    else process.stdout.write(`  info no tokens configured\n`);
    if (data.docs) note(data.docs.chunks.length > 0, `docs: ${data.docs.chunks.length} chunks`);
    else process.stdout.write(`  info no docs configured\n`);
    const teamAliases = [...data.aliases.components, ...data.aliases.props].filter((a) => a.source === 'team').length;
    process.stdout.write(`  info aliases: ${teamAliases} team, ${data.aliases.components.length + data.aliases.props.length - teamAliases} lexicon\n`);

    const fresh = checkFreshness(data);
    note(fresh.catalog !== 'stale', `catalog freshness: ${fresh.catalog}`);
    if (fresh.tokens !== 'none') note(fresh.tokens !== 'stale', `tokens freshness: ${fresh.tokens}`);
    if (fresh.docs !== 'none') note(fresh.docs !== 'stale', `docs freshness: ${fresh.docs}`);
    if (fresh.codeConnect !== 'none') note(fresh.codeConnect !== 'stale', `code connect freshness: ${fresh.codeConnect}`);
    for (const d of fresh.details) process.stdout.write(`       ${d}\n`);
  }

  process.stdout.write(`\n${problems === 0 ? 'all checks passed' : `${problems} problem(s)`}\n`);
  if (problems > 0) process.exit(1);
}

const GENERATE_TARGETS: GenerateTarget[] = ['agents-md', 'llms-txt', 'skill', 'editor-rules', 'well-known', 'all'];

async function generate(
  configPath: string | undefined,
  system: string | undefined,
  what: string | undefined,
  target: string | undefined,
  force: boolean,
  serverUrl: string | undefined,
): Promise<void> {
  if (!what || !GENERATE_TARGETS.includes(what as GenerateTarget)) {
    fail(`generate needs a target: ${GENERATE_TARGETS.join(' | ')}`);
  }
  const loaded = loadDsConfig(configPath);
  const registry = buildRegistry(loaded);
  let data;
  try {
    data = registry.get(system);
  } catch (err) {
    fail((err as Error).message);
  }
  const outDir = resolve(target ?? process.cwd());
  const result = runGenerate(data, { target: what as GenerateTarget, outDir, force, serverUrl });
  for (const f of result.written) process.stdout.write(`  wrote ${f}\n`);
  for (const f of result.skipped) process.stdout.write(`  skipped ${f} (exists and was not generated by this tool; use --force)\n`);
  for (const n of result.notes) process.stdout.write(`  note ${n}\n`);
  process.stdout.write(`generated ${what} for "${data.id}" into ${outDir}\n`);
}

main().catch((err) => fail((err as Error).stack ?? String(err)));
